<?php

namespace AppBundle\Repository;

/**
 * VolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolunteerRepository extends \Doctrine\ORM\EntityRepository
{
}
